from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from pymsch import Content

from yamig import __version__
from yamig.utils.const import DISPLAY_RESOLUTIONS, DISPLAYS


@dataclass
class YamigParams:
    # I/O
    input_path: Path
    output_path: Path
    debug_path: Path | None
    to_clipboard: bool

    # Image params
    resolution: tuple[int, int] # in px
    max_colors: int 
    dispersion_threshold: int
    min_region_size: int

    # Schema params
    display: Literal[
        Content.TILE_LOGIC_DISPLAY,
        Content.LOGIC_DISPLAY,
        Content.LARGE_LOGIC_DISPLAY
    ]
    processor: Literal[
        Content.MICRO_PROCESSOR,
        Content.LOGIC_PROCESSOR,
        Content.HYPER_PROCESSOR,
    ]
    max_script_len: int
    schema_name: str | None
    schema_description: str | None

    def validate_input_path(self):
        self.input_path = Path(self.input_path).absolute()

        if not self.input_path.exists():
            raise FileNotFoundError(f'Input file {self.input_path} not found!')
        
        if not self.input_path.is_file():
            raise FileNotFoundError(f'Input file {self.input_path} is not file!')
    
    def validate_output_path(self):
        self.output_path = Path(self.output_path).absolute()

        self.output_path.parent.mkdir(exist_ok=True, parents=True)
        self.output_path.touch(exist_ok=True)
    
    def validate_debug_path(self):
        if self.debug_path is None:
            return
        
        self.debug_path = Path(self.debug_path).absolute()
        self.debug_path.mkdir(parents=True, exist_ok=True)
    
    def validate_display(self):
        if self.display not in (
            Content.TILE_LOGIC_DISPLAY,
            Content.LOGIC_DISPLAY,
            Content.LARGE_LOGIC_DISPLAY
        ):
            raise ValueError(f'Invalid display: {self.display}')
    
    def validate_resolution(self):
        if self.resolution[0] <= 0 or self.resolution[1] <= 0:
            raise ValueError(f'Resolution cannot be lower than 1, got {self.resolution}')
        
        display_resolution = DISPLAY_RESOLUTIONS[self.display]

        if (self.resolution[0] % display_resolution != 0
            or self.resolution[1] % display_resolution != 0):
            self.resolution = (
                round(self.resolution[0] / display_resolution) * display_resolution,
                round(self.resolution[1] / display_resolution) * display_resolution
            )

        #TODO: resolution (in blocks) higher than processor range check
    
    def validate_max_colors(self):
        if not (1 <= self.max_colors <= 255):
            raise ValueError(f'Max colors value must be 1-255, got {self.max_colors}')
    
    def validate_dispersion_threshold(self):
        if not self.dispersion_threshold > 0:
            raise ValueError(
                f'Dispersion threshold value must be >0, got {self.dispersion_threshold}'
            )

    def validate_min_region_size(self):
        if not self.min_region_size > 0:
            raise ValueError(f'Min region size value must be >0, got {self.min_region_size}')
 
    def validate_processor(self):
        if self.processor not in (
            Content.MICRO_PROCESSOR,
            Content.LOGIC_PROCESSOR,
            Content.HYPER_PROCESSOR,
        ):
            raise ValueError(f'Invalid processor: {self.processor}')
    
    def validate_max_script_len(self):
        if not (3 <= self.max_script_len <= 1000):
            raise ValueError(f'Max script length value must be 3-1000, got {self.max_script_len}')
    
    def validate_schema_name(self):
        if self.schema_name is None:
            self.schema_name = (
                f"{self.input_path.stem} "
                f"{self.resolution[0]}x{self.resolution[1]}"
            )
    
    def validate_schema_description(self):
        if self.schema_description is None:
            self.schema_description = (
                f"File: {str(self.input_path.name)}\n"
                f"Resolution: {self.resolution[0]}x{self.resolution[1]}\n"
                f"Display: {self.display.name}\n"
                f"Processor: {self.processor.name}\n"
                f"Max colors: {self.max_colors}\n"
                f"Dispersion threshold: {self.dispersion_threshold}\n"
                f"Min region size: {self.min_region_size}\n"
                f"Max script length: {self.max_script_len}\n"
            )
        
        self.schema_description += (
            f"\n\nGenerated by yamig v{__version__}\n"
            f"GitHub: https://github.com/wandderq/yamig"
        )
    


    def __post_init__(self):
        self.validate_input_path()
        self.validate_output_path()
        self.validate_debug_path()
        self.validate_display()
        self.validate_resolution()
        self.validate_max_colors()
        self.validate_dispersion_threshold()
        self.validate_min_region_size()
        self.validate_processor()
        self.validate_max_script_len()
        self.validate_schema_name()
        self.validate_schema_description()